version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "MichiBaum"
    labels:
      - "dependabot-update"
    target-branch: "development"
