namespace ManagedWinapi.Audio.Mixer {
    /// <summary>
    ///     The type of a mixer control.
    ///     You can find descriptions for most of these types on
    ///     http://www.borg.com/~jglatt/tech/mixer.htm.
    /// </summary>
    public enum MixerControlType {
        ///
        MIXERCONTROL_CT_SC_SWITCH_BOOLEAN = 0x00000000,

        ///
        MIXERCONTROL_CT_SC_SWITCH_BUTTON = 0x01000000,

        ///
        MIXERCONTROL_CT_SC_METER_POLLED = 0x00000000,

        ///
        MIXERCONTROL_CT_SC_TIME_MICROSECS = 0x00000000,

        ///
        MIXERCONTROL_CT_SC_TIME_MILLISECS = 0x01000000,

        ///
        MIXERCONTROL_CT_SC_LIST_SINGLE = 0x00000000,

        ///
        MIXERCONTROL_CT_SC_LIST_MULTIPLE = 0x01000000,

        ///
        MIXERCONTROL_CT_UNITS_CUSTOM = 0x00000000,

        ///
        MIXERCONTROL_CT_UNITS_BOOLEAN = 0x00010000,

        ///
        MIXERCONTROL_CT_UNITS_SIGNED = 0x00020000,

        ///
        MIXERCONTROL_CT_UNITS_UNSIGNED = 0x00030000,

        ///
        MIXERCONTROL_CT_UNITS_DECIBELS = 0x00040000, /* in 10ths */

        ///
        MIXERCONTROL_CT_UNITS_PERCENT = 0x00050000, /* in 10ths */

        ///
        MIXERCONTROL_CONTROLTYPE_CUSTOM = MixerControlClass.CUSTOM | MIXERCONTROL_CT_UNITS_CUSTOM,

        ///
        MIXERCONTROL_CONTROLTYPE_BOOLEANMETER =
            MixerControlClass.METER | MIXERCONTROL_CT_SC_METER_POLLED | MIXERCONTROL_CT_UNITS_BOOLEAN,

        ///
        MIXERCONTROL_CONTROLTYPE_SIGNEDMETER =
            MixerControlClass.METER | MIXERCONTROL_CT_SC_METER_POLLED | MIXERCONTROL_CT_UNITS_SIGNED,

        ///
        MIXERCONTROL_CONTROLTYPE_PEAKMETER = MIXERCONTROL_CONTROLTYPE_SIGNEDMETER + 1,

        ///
        MIXERCONTROL_CONTROLTYPE_UNSIGNEDMETER = MixerControlClass.METER | MIXERCONTROL_CT_SC_METER_POLLED |
                                                 MIXERCONTROL_CT_UNITS_UNSIGNED,

        ///
        MIXERCONTROL_CONTROLTYPE_BOOLEAN = MixerControlClass.SWITCH | MIXERCONTROL_CT_SC_SWITCH_BOOLEAN |
                                           MIXERCONTROL_CT_UNITS_BOOLEAN,

        ///
        MIXERCONTROL_CONTROLTYPE_ONOFF = MIXERCONTROL_CONTROLTYPE_BOOLEAN + 1,

        ///
        MIXERCONTROL_CONTROLTYPE_MUTE = MIXERCONTROL_CONTROLTYPE_BOOLEAN + 2,

        ///
        MIXERCONTROL_CONTROLTYPE_MONO = MIXERCONTROL_CONTROLTYPE_BOOLEAN + 3,

        ///
        MIXERCONTROL_CONTROLTYPE_LOUDNESS = MIXERCONTROL_CONTROLTYPE_BOOLEAN + 4,

        ///
        MIXERCONTROL_CONTROLTYPE_STEREOENH = MIXERCONTROL_CONTROLTYPE_BOOLEAN + 5,

        ///
        MIXERCONTROL_CONTROLTYPE_BUTTON =
            MixerControlClass.SWITCH | MIXERCONTROL_CT_SC_SWITCH_BUTTON | MIXERCONTROL_CT_UNITS_BOOLEAN,

        ///
        MIXERCONTROL_CONTROLTYPE_DECIBELS = MixerControlClass.NUMBER | MIXERCONTROL_CT_UNITS_DECIBELS,

        ///
        MIXERCONTROL_CONTROLTYPE_SIGNED = MixerControlClass.NUMBER | MIXERCONTROL_CT_UNITS_SIGNED,

        ///
        MIXERCONTROL_CONTROLTYPE_UNSIGNED = MixerControlClass.NUMBER | MIXERCONTROL_CT_UNITS_UNSIGNED,

        ///
        MIXERCONTROL_CONTROLTYPE_PERCENT = MixerControlClass.NUMBER | MIXERCONTROL_CT_UNITS_PERCENT,

        ///
        MIXERCONTROL_CONTROLTYPE_SLIDER = MixerControlClass.SLIDER | MIXERCONTROL_CT_UNITS_SIGNED,

        ///
        MIXERCONTROL_CONTROLTYPE_PAN = MixerControlClass.SLIDER + 1,

        ///
        MIXERCONTROL_CONTROLTYPE_QSOUNDPAN = MIXERCONTROL_CONTROLTYPE_SLIDER + 2,

        ///
        MIXERCONTROL_CONTROLTYPE_FADER = MixerControlClass.FADER | MIXERCONTROL_CT_UNITS_UNSIGNED,

        ///
        MIXERCONTROL_CONTROLTYPE_VOLUME = MIXERCONTROL_CONTROLTYPE_FADER + 1,

        ///
        MIXERCONTROL_CONTROLTYPE_BASS = MIXERCONTROL_CONTROLTYPE_FADER + 2,

        ///
        MIXERCONTROL_CONTROLTYPE_TREBLE = MIXERCONTROL_CONTROLTYPE_FADER + 3,

        ///
        MIXERCONTROL_CONTROLTYPE_EQUALIZER = MIXERCONTROL_CONTROLTYPE_FADER + 4,

        ///
        MIXERCONTROL_CONTROLTYPE_SINGLESELECT =
            MixerControlClass.LIST | MIXERCONTROL_CT_SC_LIST_SINGLE | MIXERCONTROL_CT_UNITS_BOOLEAN,

        ///
        MIXERCONTROL_CONTROLTYPE_MUX = MIXERCONTROL_CONTROLTYPE_SINGLESELECT + 1,

        ///
        MIXERCONTROL_CONTROLTYPE_MULTIPLESELECT =
            MixerControlClass.LIST | MIXERCONTROL_CT_SC_LIST_MULTIPLE | MIXERCONTROL_CT_UNITS_BOOLEAN,

        ///
        MIXERCONTROL_CONTROLTYPE_MIXER = MIXERCONTROL_CONTROLTYPE_MULTIPLESELECT + 1,

        ///
        MIXERCONTROL_CONTROLTYPE_MICROTIME = MixerControlClass.TIME | MIXERCONTROL_CT_SC_TIME_MICROSECS |
                                             MIXERCONTROL_CT_UNITS_UNSIGNED,

        ///
        MIXERCONTROL_CONTROLTYPE_MILLITIME = MixerControlClass.TIME | MIXERCONTROL_CT_SC_TIME_MILLISECS |
                                             MIXERCONTROL_CT_UNITS_UNSIGNED
    }
}