//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Switcheroo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class language_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public language_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Switcheroo.Properties.language_en", typeof(language_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Alt + S to search.
        /// </summary>
        public static string MainWindow_AltTabPressed_Press_Alt___S_to_search {
            get {
                return ResourceManager.GetString("MainWindow_AltTabPressed_Press_Alt___S_to_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switcheroo v{0} is available (you have v{1}).
        ///
        ///Do you want to download it?.
        /// </summary>
        public static string MainWindow_CheckForUpdates_ {
            get {
                return ResourceManager.GetString("MainWindow_CheckForUpdates_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey already in use.
        /// </summary>
        public static string MainWindow_SetUpHotKey_Hotkey_already_in_use {
            get {
                return ResourceManager.GetString("MainWindow_SetUpHotKey_Hotkey_already_in_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current hotkey for activating Switcheroo is in use by another program..
        /// </summary>
        public static string MainWindow_SetUpHotKey_The_current_hotkey_for_activating_Switcheroo_is_in_use_by_another_program_ {
            get {
                return ResourceManager.GetString("MainWindow_SetUpHotKey_The_current_hotkey_for_activating_Switcheroo_is_in_use_by_" +
                        "another_program_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change the hotkey by right-clicking the Switcheroo icon in the system tray and choosing &apos;Options&apos;..
        /// </summary>
        public static string MainWindow_SetUpHotKey_You_can_change_the_hotkey_by_right_clicking_the_Switcheroo_icon_in_the_system_tray_and_choosing__Options__ {
            get {
                return ResourceManager.GetString("MainWindow_SetUpHotKey_You_can_change_the_hotkey_by_right_clicking_the_Switcheroo" +
                        "_icon_in_the_system_tray_and_choosing__Options__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainWindow_SetUpNotifyIcon_About {
            get {
                return ResourceManager.GetString("MainWindow_SetUpNotifyIcon_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MainWindow_SetUpNotifyIcon_Exit {
            get {
                return ResourceManager.GetString("MainWindow_SetUpNotifyIcon_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string MainWindow_SetUpNotifyIcon_Options {
            get {
                return ResourceManager.GetString("MainWindow_SetUpNotifyIcon_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run on Startup.
        /// </summary>
        public static string MainWindow_SetUpNotifyIcon_Run_on_Startup {
            get {
                return ResourceManager.GetString("MainWindow_SetUpNotifyIcon_Run_on_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switcheroo.
        /// </summary>
        public static string MainWindow_SetUpNotifyIcon_Switcheroo {
            get {
                return ResourceManager.GetString("MainWindow_SetUpNotifyIcon_Switcheroo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose another..
        /// </summary>
        public static string OptionsWindow_Ok_Click_Please_choose_another_ {
            get {
                return ResourceManager.GetString("OptionsWindow_Ok_Click_Please_choose_another_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut already in use.
        /// </summary>
        public static string OptionsWindow_Ok_Click_Shortcut_already_in_use {
            get {
                return ResourceManager.GetString("OptionsWindow_Ok_Click_Shortcut_already_in_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! The selected shortcut for activating Switcheroo is in use by another program..
        /// </summary>
        public static string OptionsWindow_Ok_Click_Sorry__The_selected_shortcut_for_activating_Switcheroo_is_in_use_by_another_program_ {
            get {
                return ResourceManager.GetString("OptionsWindow_Ok_Click_Sorry__The_selected_shortcut_for_activating_Switcheroo_is_" +
                        "in_use_by_another_program_", resourceCulture);
            }
        }
    }
}
